# Generated by Django 3.0.2 on 2020-01-18 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PageIt', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='page',
        ),
    ]
