# Generated by Django 3.0.2 on 2020-01-18 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PageIt', '0004_page'),
    ]

    operations = [
        migrations.RenameField(
            model_name='page',
            old_name='data',
            new_name='page_data',
        ),
    ]
