# Generated by Django 3.0.2 on 2020-01-18 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PageIt', '0007_auto_20200118_0639'),
    ]

    operations = [
        migrations.RenameField(
            model_name='page',
            old_name='page_data',
            new_name='data',
        ),
        migrations.RenameField(
            model_name='page',
            old_name='page',
            new_name='id',
        ),
    ]
